In [13]:
from IPython.core.interactiveshell import InteractiveShell
import pandas as pd, numpy as np
import openpyxl
InteractiveShell.ast_node_interactivity = 'all'

In [14]:
df = pd.read_csv('new_team.csv')

In [15]:
df
type(df)

name team  Q1  Q2  Q3  Q4
0     Aaron    A  96  75  55   8
1       Ack    A  57  60  18  84
2      Acob    B  61  95  94   8
3      Adam    C  90  32  47  39
4     Aiden    D  20  31  62  68
..      ...  ...  ..  ..  ..  ..
95     Toby    A  52  27  17  68
96    Tommy    C  29  44  28  76
97    Tyler    A  75  16  44  63
98  William    C  80  68   3  26
99  Zachary    E  12  71  85  93

[100 rows x 6 columns]

pandas.core.frame.DataFrame

In [16]:
wb = openpyxl.load_workbook('new000607.xlsx')
wb.worksheets

[<Worksheet "Sheet1">]

In [17]:
ws = wb['Sheet1']

In [18]:
ws['A1']

<Cell 'Sheet1'.A1>

In [19]:
help(ws['A1'])

Help on Cell in module openpyxl.cell.cell object:

class Cell(openpyxl.styles.styleable.StyleableObject)
 |  Cell(worksheet, row=None, column=None, value=None, style_array=None)
 |  
 |  Describes cell associated properties.
 |  
 |  Properties of interest include style, type, value, and address.
 |  
 |  Method resolution order:
 |      Cell
 |      openpyxl.styles.styleable.StyleableObject
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, worksheet, row=None, column=None, value=None, style_array=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __repr__(self)
 |      Return repr(self).
 |  
 |  check_error(self, value)
 |      Tries to convert Error" else N/A
 |  
 |  check_string(self, value)
 |      Check string coding, length, and line break character
 |  
 |  offset(self, row=0, column=0)
 |      Returns a cell location relative to this cell.
 |      
 |      :param row: number of rows to offset
 |      :type row: i

In [20]:
ws['A2'].value
ws['A2'].internal_value

'2022-05-06'

'2022-05-06'

In [21]:
cell = ws['B3']
cell

<Cell 'Sheet1'.B3>

In [22]:
cell.col_idx
cell.column
cell.column_letter
cell.base_date
cell.coordinate
cell.row
cell.data_type

2

2

'B'

datetime.datetime(1899, 12, 30, 0, 0)

'B3'

3

'n'

In [23]:
new_wb = openpyxl.Workbook.create_sheet('newsheet')

AttributeError: 'str' object has no attribute 'read_only'

In [24]:
l = [1,2,3,4,5]
arrl = np.array(l)
l
arrl
arrl[0] = 100
l
arrl

[1, 2, 3, 4, 5]

array([1, 2, 3, 4, 5])

[1, 2, 3, 4, 5]

array([100,   2,   3,   4,   5])

In [29]:
arry = np.array([0,0,1,1,0])
arrl[arry==0]

array([100,   2,   5])

In [ ]:
from collections import Counter