In [18]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

X在运行X[:]=X+Y前后id相同，说明指向一个内存区域。
使用X=X+Y与X += Y的区别

In [ ]:
a1 = np.arange(4)
a2 = np.arange(3,7)
a1,a2
np.row_stack((a1,a2))

In [19]:
x = np.arange(60).reshape(3,1,4,5)

In [20]:
x,x.T,x.transpose()  # 转置后形成了5页4行三列，是0轴和-1轴的交换？非也，是形状的完全倒置
x.shape
x.T.shape

(array([[[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]]],
 
 
        [[[20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39]]],
 
 
        [[[40, 41, 42, 43, 44],
          [45, 46, 47, 48, 49],
          [50, 51, 52, 53, 54],
          [55, 56, 57, 58, 59]]]]),
 array([[[[ 0, 20, 40]],
 
         [[ 5, 25, 45]],
 
         [[10, 30, 50]],
 
         [[15, 35, 55]]],
 
 
        [[[ 1, 21, 41]],
 
         [[ 6, 26, 46]],
 
         [[11, 31, 51]],
 
         [[16, 36, 56]]],
 
 
        [[[ 2, 22, 42]],
 
         [[ 7, 27, 47]],
 
         [[12, 32, 52]],
 
         [[17, 37, 57]]],
 
 
        [[[ 3, 23, 43]],
 
         [[ 8, 28, 48]],
 
         [[13, 33, 53]],
 
         [[18, 38, 58]]],
 
 
        [[[ 4, 24, 44]],
 
         [[ 9, 29, 49]],
 
         [[14, 34, 54]],
 
         [[19, 39, 59]]]]),
 array([[[[ 0, 20, 40]],
 
         [[ 5, 25, 4

(3, 1, 4, 5)

(5, 4, 1, 3)

In [21]:
y = x.swapaxes(0,1)
x,y

(array([[[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]]],
 
 
        [[[20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39]]],
 
 
        [[[40, 41, 42, 43, 44],
          [45, 46, 47, 48, 49],
          [50, 51, 52, 53, 54],
          [55, 56, 57, 58, 59]]]]),
 array([[[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]],
 
         [[20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39]],
 
         [[40, 41, 42, 43, 44],
          [45, 46, 47, 48, 49],
          [50, 51, 52, 53, 54],
          [55, 56, 57, 58, 59]]]]))

In [22]:
z = np.arange(1,13,1).reshape(3,4)
z
np.moveaxis(z,0,1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [23]:
z
np.resize(z,(4,8))  # 所有元素循环填充
np.resize(z,(2,3))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8]])

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.append(z,values=[222,3333,22,44])
z

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,  222, 3333,   22,   44])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
np.append(z,values=[[222,3333,22,44]])  # 不指定axis时，数组会被展开，都是成为一维数组
z

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,  222, 3333,   22,   44])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
np.append(z,values=[[222,3333,22,44],[22223,999,77,99]])
z

array([    1,     2,     3,     4,     5,     6,     7,     8,     9,
          10,    11,    12,   222,  3333,    22,    44, 22223,   999,
          77,    99])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
np.append(z,values=[[222,3333,22,44]], axis=0)  # 维数相等才可，相当于vstack

array([[   1,    2,    3,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12],
       [ 222, 3333,   22,   44]])

In [28]:
np.append(z,values=[[222],[3333],[22]], axis=1) # 相当于hstack，在添加的轴上数量相等，这里必须是一个三行一列的列向量

array([[   1,    2,    3,    4,  222],
       [   5,    6,    7,    8, 3333],
       [   9,   10,   11,   12,   22]])

In [29]:
np.insert(z,obj=0,values=[[222],[3333],[22]], axis=1)  # 不是只应该插入一组吗，为什么会被广播？？？跟想象不一样
z

array([[ 222, 3333,   22,    1,    2,    3,    4],
       [ 222, 3333,   22,    5,    6,    7,    8],
       [ 222, 3333,   22,    9,   10,   11,   12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
np.insert(z,obj=0,values=[99,88,77,66])

array([99, 88, 77, 66,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
np.insert(z,obj=1,values=[99,88,77,66], axis=0) # 与append不一样，插入的不是同维数的数组，而是一个一维的即可

array([[ 1,  2,  3,  4],
       [99, 88, 77, 66],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
np.insert(z,obj=0,values=[98,97,96], axis=1)

array([[98,  1,  2,  3,  4],
       [97,  5,  6,  7,  8],
       [96,  9, 10, 11, 12]])

In [33]:
np.insert(z,obj=0,values=2222, axis=1) # 广播机制

array([[2222,    1,    2,    3,    4],
       [2222,    5,    6,    7,    8],
       [2222,    9,   10,   11,   12]])

In [34]:
np.append(z,333333,axis=0)  # append不支持广播机制

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 0 dimension(s)

In [ ]:
np.delete(z,11) # 这里的11是索引，而不是具体值

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.delete(z,1,axis=1)

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [ ]:
np.delete(z,1,axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
w = np.random.randint(1,9,size=(4,5))
w

array([[3, 2, 3, 4, 6],
       [5, 4, 3, 4, 5],
       [8, 1, 1, 6, 2],
       [8, 1, 4, 6, 5]])

In [ ]:
np.unique(w)

array([1, 2, 3, 4, 5, 6, 8])

In [ ]:
np.unique(w,return_index=True)

(array([1, 2, 3, 4, 5, 6, 8]), array([11,  1,  0,  3,  5,  4, 10]))

In [ ]:
np.unique(w,return_index=True, return_inverse=True)

(array([1, 2, 3, 4, 5, 6, 8]),
 array([11,  1,  0,  3,  5,  4, 10]),
 array([2, 1, 2, 3, 5, 4, 3, 2, 3, 4, 6, 0, 0, 5, 1, 6, 0, 3, 5, 4]))

In [ ]:
np.unique(w,return_index=True, return_inverse=True, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 8]),
 array([11,  1,  0,  3,  5,  4, 10]),
 array([2, 1, 2, 3, 5, 4, 3, 2, 3, 4, 6, 0, 0, 5, 1, 6, 0, 3, 5, 4]),
 array([3, 2, 3, 4, 3, 3, 2]))

In [36]:
np.where(z>4)

(array([1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3]))

In [37]:
z[_]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
np.extract(z>4,z) # 相当于把获得布尔索引和用布尔索引获取数据两步合一

array([ 5,  6,  7,  8,  9, 10, 11, 12])