In [2]:
from IPython.core.interactiveshell import InteractiveShell
import numpy as np
from numpy import matlib as ml
InteractiveShell.ast_node_interactivity = 'all'

In [4]:
ml.empty((3,4))

matrix([[1.20945752e-315, 0.00000000e+000, 1.01855798e-312,
         9.54898106e-313],
        [1.18831764e-312, 1.03977794e-312, 1.23075756e-312,
         1.16709769e-312],
        [1.10343781e-312, 9.76118064e-313, 1.14587773e-312,
         1.90979621e-312]])

In [5]:
ml.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
_.T

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
np.eye(4,6)
ml.eye(4,6)
ml.eye(6,4)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

matrix([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.]])

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
np.identity(5)
ml.identity(5) # 这才是单位矩阵

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
from torch import seed


np.random.random(size=(4,6))
ml.rand((4,6))

array([[0.55673682, 0.47321788, 0.36589801, 0.8324459 , 0.77219405,
        0.65244548],
       [0.77796952, 0.59463591, 0.55556469, 0.86452027, 0.76408704,
        0.88495944],
       [0.07730113, 0.45460841, 0.94089146, 0.46738953, 0.71189579,
        0.86572938],
       [0.97588379, 0.13457867, 0.70394843, 0.73996201, 0.38686597,
        0.85945742]])

matrix([[0.54909007, 0.0144882 , 0.08340921, 0.11954747, 0.89604761,
         0.14360532],
        [0.59502451, 0.55315909, 0.08724025, 0.77877251, 0.54992124,
         0.64362819],
        [0.59656294, 0.06997455, 0.62713239, 0.00741951, 0.21526429,
         0.86044122],
        [0.8060743 , 0.48671853, 0.8736125 , 0.93859718, 0.453243  ,
         0.99445753]])

In [16]:
ar =np.arange(16).reshape(4,4)
ar
ma = np.asmatrix(ar)
ma

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [17]:
ar2 = np.asarray(ma)
ar2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])