In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
ar = np.random.random(100)
ar

array([0.51368147, 0.50585369, 0.30690288, 0.59791721, 0.81805118,
       0.65853472, 0.18592692, 0.83469689, 0.25547845, 0.02463054,
       0.10130172, 0.3857251 , 0.46524589, 0.07898223, 0.67353761,
       0.12349832, 0.00702679, 0.11776715, 0.68531145, 0.97960812,
       0.20376937, 0.73066677, 0.3840856 , 0.50757301, 0.8112966 ,
       0.91702144, 0.92739585, 0.39370293, 0.71086316, 0.30404207,
       0.86649473, 0.39560111, 0.28939405, 0.68947333, 0.55641968,
       0.74621824, 0.4276046 , 0.30444713, 0.80946244, 0.42674335,
       0.7920513 , 0.79052161, 0.19831124, 0.86623012, 0.85986294,
       0.20591346, 0.96111015, 0.16127115, 0.43404069, 0.83139151,
       0.249833  , 0.61071085, 0.33498865, 0.76063856, 0.19256714,
       0.44467176, 0.64557635, 0.93825601, 0.05891405, 0.11471895,
       0.55739863, 0.99538652, 0.97393886, 0.99921281, 0.28683679,
       0.43614013, 0.35903779, 0.74192012, 0.25623408, 0.23691733,
       0.60938467, 0.95181834, 0.04119707, 0.4363685 , 0.13187

In [3]:
ar.sum()

49.67991764807154

In [4]:
X = np.arange(16).reshape(4,4)
X
X.sum()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

120

In [121]:
X.sum(axis=0)

array([24, 28, 32, 36])

In [122]:
X.sum(axis=1)

array([ 6, 22, 38, 54])

In [123]:
np.mean(X,axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

In [5]:
np.prod(X+1)

20922789888000

In [6]:
np.cumprod(X+1)

array([             1,              2,              6,             24,
                  120,            720,           5040,          40320,
               362880,        3628800,       39916800,      479001600,
           6227020800,    87178291200,  1307674368000, 20922789888000])

In [7]:
np.cumsum(X)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120])

In [8]:
np.median(X)

7.5

In [128]:
np.percentile(X,q=50)

7.5

In [9]:
np.percentile(X,q=[10,20,30,40,50,60,70,80.90])

array([ 1.5  ,  3.   ,  4.5  ,  6.   ,  7.5  ,  9.   , 10.5  , 12.135])

In [130]:
np.std(X)

4.6097722286464435

In [131]:
np.std(X,axis=0)

array([4.47213595, 4.47213595, 4.47213595, 4.47213595])

In [132]:
np.std(X,axis=1)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399])

In [10]:
np.argmax(X)

15

In [134]:
np.argmin(X)

0

In [20]:
X
np.random.shuffle(X) #原地操作，在第一维上。

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [21]:
X

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
np.sort(X,axis=0)  # 非原地操作

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
X

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
np.sort(X,axis=0) #不传参的话，不改变


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
X

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
x = X.reshape(16,)
x

array([ 4,  5,  6,  7,  0,  1,  2,  3,  8,  9, 10, 11, 12, 13, 14, 15])

In [142]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [143]:
x

array([ 8,  9, 10, 11,  4,  5,  6,  7,  0,  1,  2,  3, 12, 13, 14, 15])

In [144]:
np.argsort(x)

array([ 8,  9, 10, 11,  4,  5,  6,  7,  0,  1,  2,  3, 12, 13, 14, 15])

In [29]:
x

array([ 4,  5,  6,  7,  0,  1,  2,  3,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
np.partition(x,3)

array([ 0,  1,  2,  3,  4,  7,  6,  5,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
np.argpartition(x,3)

array([ 4,  5,  6,  7,  0,  3,  2,  1,  8,  9, 10, 11, 12, 13, 14, 15])

In [148]:
np.argsort(x)

array([ 8,  9, 10, 11,  4,  5,  6,  7,  0,  1,  2,  3, 12, 13, 14, 15])

In [149]:
0,x
np.random.shuffle(x)
1,x
np.sort(x)
2,x
x.sort()
3,x

(0, array([ 8,  9, 10, 11,  4,  5,  6,  7,  0,  1,  2,  3, 12, 13, 14, 15]))

(1, array([ 5,  0, 13, 14,  6, 11, 15,  2,  3,  4, 10,  9,  1,  7, 12,  8]))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

(2, array([ 5,  0, 13, 14,  6, 11, 15,  2,  3,  4, 10,  9,  1,  7, 12,  8]))

(3, array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]))

In [155]:
np.random.shuffle(x)


x

array([ 4,  9,  3,  6,  1, 11,  0,  5, 10, 14, 13,  2, 15,  8,  7, 12])

In [156]:
ind = [0,1,0,2,0]
x
x.sort(axis=0) #原地操作
x

array([ 4,  9,  3,  6,  1, 11,  0,  5, 10, 14, 13,  2, 15,  8,  7, 12])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [157]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [160]:
np.random.shuffle(y)

In [161]:
y

array([1, 4, 2, 0, 3])

In [162]:
y.sort()
y

array([0, 1, 2, 3, 4])

In [163]:
y

array([0, 1, 2, 3, 4])

In [164]:
y[ind]

array([0, 1, 0, 2, 0])

In [165]:
ind2 = [[2,3,4],[2,1,0]]
y[ind2]

array([[2, 3, 4],
       [2, 1, 0]])

In [166]:
y

array([0, 1, 2, 3, 4])

In [169]:
z = np.expand_dims(y,axis=1)  # 非原地操作
y
z

array([0, 1, 2, 3, 4])

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [170]:
w = np.expand_dims(z,axis=0)

In [171]:
w

array([[[0],
        [1],
        [2],
        [3],
        [4]]])

In [172]:
w = np.expand_dims(z,axis=1)
w

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]]])

In [174]:
x = x.reshape(2,8)

In [179]:
x
y = np.expand_dims(x,axis=0)
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]])

In [180]:
z = np.squeeze(y)
z

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [195]:
x.data
x.real
x.imag
x.itemsize

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

8

In [204]:
x=np.arange(32).reshape((8,4))
x
print (x[np.ix_([1,5,7,2],[0,3,1,2])]) # 不同于整数数组索引，整数数组索引得到是4个，且行列取值长度相等，
# 而这种方法得到的是4行4列，且可不同长度

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [208]:
for i in np.nditer(x,flags=['external_loop']):
    print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


In [209]:
for i in np.nditer(x,flags=['external_loop'], order='F'):
    print(i)

[ 0  4  8 12 16 20 24 28]
[ 1  5  9 13 17 21 25 29]
[ 2  6 10 14 18 22 26 30]
[ 3  7 11 15 19 23 27 31]


In [210]:
for i in np.nditer(x,flags=['external_loop'], order='C'):
    print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


In [213]:
xc = x.ravel(order='C')   #  !!!C风格是视图，F风格是复制
xf = x.ravel(order='F')
x,xc,xf

(array([[100, 100, 100, 100],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]]),
 array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31]),
 array([100,   4,   8,  12,  16,  20,  24,  28, 100,   5,   9,  13,  17,
         21,  25,  29, 100,   6,  10,  14,  18,  22,  26,  30, 100,   7,
         11,  15,  19,  23,  27,  31]))

In [212]:
x[0] = 100
x,xc,xf

(array([[100, 100, 100, 100],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]]),
 array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31]),
 array([ 0,  4,  8, 12, 16, 20, 24, 28,  1,  5,  9, 13, 17, 21, 25, 29,  2,
         6, 10, 14, 18, 22, 26, 30,  3,  7, 11, 15, 19, 23, 27, 31]))