In [2]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [3]:
a = np.random.randint(1,20,size=(10,))
b = [2,9,7,6,5]
a,b

(array([ 7, 17, 16,  3, 11,  6, 18,  2, 18,  2]), [2, 9, 7, 6, 5])

In [ ]:
c_full = np.convolve(a, b, mode='full') # 完全卷积  a + (k - 1)
c_same = np.convolve(a, b, mode='same')  # 同维卷积 a
c_valid = np.convolve(a, b, mode='valid') # 有效卷积 a - (k - 1)
c_full
c_full.shape
c_same
c_same.shape
c_valid
c_valid.shape

In [ ]:
# 多维卷积  ？？？

In [19]:
x = np.arange(1,10).reshape(3,3)
y = np.ones((7, 7))
x,y
x = np.matrix(x)
y = np.matrix(y)
x,y

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]]))

(matrix([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 matrix([[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]))

In [ ]:
len(x)
len(y)
z = np.convolve(y, x, 'valid')
z