In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
a = np.arange(12).reshape(3,4)

In [29]:
b = np.rollaxis(a,0,start=1)

In [21]:
b
a

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
c = np.tile(a,(2,2,2))
c

array([[[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11]],

       [[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11]]])

In [26]:
np.vstack([a]*2)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
np.vstack(a*2)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [30]:
np.vstack([a,b])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
np.vsplit(a,[-2])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]

In [10]:
np.split(a,[-1],axis=1)

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [11]:
np.split(a,[-1],axis=0)


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

In [12]:
np.concatenate([a,b])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
np.concatenate([a,b],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [14]:
a + b
a * b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [16]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
b = np.arange(2,14).reshape(3,4)

In [32]:
a + b
a * b
a / b
a // b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

/tmp/ipykernel_8483/2087436099.py:3: RuntimeWarning: invalid value encountered in divide
  a / b


array([[nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

/tmp/ipykernel_8483/2087436099.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  a // b


array([[0, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [33]:
a.dot(b)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [ ]:
a.dot(b.T)
a
b.T

array([[ 26,  50,  74],
       [ 82, 170, 258],
       [138, 290, 442]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12],
       [ 5,  9, 13]])

In [ ]:
c = np.array([1,2,3])

In [34]:
a.dot(c)

ValueError: shapes (3,4) and (2,6,8) not aligned: 4 (dim 1) != 6 (dim 1)

In [ ]:
c.dot(a)

array([32, 38, 44, 50])

In [ ]:
a.dot(c.T)

ValueError: shapes (3,4) and (3,) not aligned: 4 (dim 1) != 3 (dim 0)

In [ ]:
d = c.reshape(1,-1)
d

array([[1, 2, 3]])

In [ ]:
d.dot(a)

array([[32, 38, 44, 50]])

In [ ]:
a.dot(d)

ValueError: shapes (3,4) and (1,3) not aligned: 4 (dim 1) != 1 (dim 0)

In [ ]:
a.dot(d.T)

ValueError: shapes (3,4) and (3,1) not aligned: 4 (dim 1) != 3 (dim 0)

In [ ]:
e = np.linspace(1,4,4)
e

array([1., 2., 3., 4.])

In [ ]:
a.dot(e)

array([ 20.,  60., 100.])

In [ ]:
e.dot(a)

ValueError: shapes (4,) and (3,4) not aligned: 4 (dim 0) != 3 (dim 0)

In [ ]:
a.dot(e)

array([ 20.,  60., 100.])

In [ ]:
np.tile(e,[2,1])

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
e

array([1., 2., 3., 4.])

In [ ]:
a.dot(e) #自动将E当作一个列向量来使用了

array([ 20.,  60., 100.])

In [ ]:
f = np.arange(16).reshape(4,-1)

In [35]:
#矩阵的逆
np.linalg.inv(a)

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
# 伪逆矩阵
a_pi = np.linalg.pinv(a)
a_pi
a.dot(a_pi)

array([[-0.3375    , -0.1       ,  0.1375    ],
       [-0.13333333, -0.03333333,  0.06666667],
       [ 0.07083333,  0.03333333, -0.00416667],
       [ 0.275     ,  0.1       , -0.075     ]])

array([[ 0.83333333,  0.33333333, -0.16666667],
       [ 0.33333333,  0.33333333,  0.33333333],
       [-0.16666667,  0.33333333,  0.83333333]])

In [ ]:
f_inv = np.linalg.inv(f)
f_inv

array([[ 1.25099990e+15, -1.50119988e+15, -7.50599938e+14,
         1.00079992e+15],
       [-2.75219977e+15,  3.75299969e+15,  7.50599938e+14,
        -1.75139986e+15],
       [ 1.75139986e+15, -3.00239975e+15,  7.50599938e+14,
         5.00399959e+14],
       [-2.50199979e+14,  7.50599938e+14, -7.50599938e+14,
         2.50199979e+14]])

In [ ]:
f.dot(f_inv)  # 为什么不是单位矩阵

array([[ 1.25 , -0.125,  0.125,  0.125],
       [ 0.25 , -0.625,  0.625,  0.625],
       [-0.75 , -0.125,  1.125,  1.125],
       [-4.75 , -0.625,  2.625,  1.625]])

In [ ]:
g = np.array([[1,4],[2,3]])
gi = np.linalg.inv(g)
g
gi
g.dot(gi)

array([[1, 4],
       [2, 3]])

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])