In [2]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [3]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])  
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [4]:
np.max(a,axis=0) # max是amax的别名

array([8, 7, 9])

In [5]:
np.max(a,axis=1)

array([7, 8, 9])

In [6]:
np.amax(a,axis=0)

array([8, 7, 9])

In [7]:
np.min(a,axis=0,keepdims=True)

array([[2, 4, 3]])

In [8]:
np.ptp(a)

7

In [9]:
np.ptp(a,axis=0)

array([6, 3, 6])

In [10]:
np.ptp(a,axis=1)

array([4, 5, 7])

In [11]:
np.percentile(a,axis=0,q=[25,50,90])

array([[2.5, 4. , 4. ],
       [3. , 4. , 5. ],
       [7. , 6.4, 8.2]])

In [12]:
np.mean,np.median
np.average #加权

(<function numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)>,
 <function numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)>)

<function numpy.average(a, axis=None, weights=None, returned=False, *, keepdims=<no value>)>

In [13]:
np.average(a,axis=0,weights=[1,2,3])

array([4.16666667, 4.5       , 6.33333333])

In [14]:
np.average(a,axis=0,weights=[3,2,1])

array([4.5, 5.5, 5. ])

In [15]:
np.std(a)

2.309401076758503

In [16]:
np.var(a)

5.333333333333333

In [17]:
np.sqrt(_)

2.309401076758503

In [18]:
np.sort
np.where(a>4)


<function numpy.sort(a, axis=-1, kind=None, order=None)>

(array([0, 0, 1, 2]), array([1, 2, 0, 2]))

In [26]:
a[_] = 99
a

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,3) (3,2) 

In [20]:
np.extract(a,a>3)

array([False,  True,  True,  True,  True, False, False,  True,  True])

In [21]:
np.extract(a>3,a)

array([99, 99, 99,  4,  4, 99])

In [22]:
b = a[0:2,...].copy()
b
b[0] =999
b
a

array([[ 3, 99, 99],
       [99,  4,  3]])

array([[999, 999, 999],
       [ 99,   4,   3]])

array([[ 3, 99, 99],
       [99,  4,  3],
       [ 2,  4, 99]])

In [23]:
a = np.arange(6)  
print ('我们的数组是：')
print (a)
print ('调用 id() 函数：')
print (id(a))
print ('a 赋值给 b：')
b = a 
print (b)
print ('b 拥有相同 id()：')
print (id(b))
print ('修改 b 的形状：')
b.shape =  3,2  
print (b)
print ('a 的形状也修改了：')
print (a)

我们的数组是：
[0 1 2 3 4 5]
调用 id() 函数：
281472979688048
a 赋值给 b：
[0 1 2 3 4 5]
b 拥有相同 id()：
281472979688048
修改 b 的形状：
[[0 1]
 [2 3]
 [4 5]]
a 的形状也修改了：
[[0 1]
 [2 3]
 [4 5]]


view会产生新的视图，可以变换形状不影响原数组，但是数据修改会影响

In [24]:
a = np.arange(6).reshape(3,2)  
print ('数组 a：')
print (a)
print ('创建 a 的视图：')
b = a.view()  
print (b)
print ('两个数组的 id() 不同：')
print ('a 的 id()：')
print (id(a))
print ('b 的 id()：' )
print (id(b))
# 修改 b 的形状，并不会修改 a
b.shape =  2,3
print ('b 的形状：')
print (b)
print ('a 的形状：')
print (a)

数组 a：
[[0 1]
 [2 3]
 [4 5]]
创建 a 的视图：
[[0 1]
 [2 3]
 [4 5]]
两个数组的 id() 不同：
a 的 id()：
281472979692080
b 的 id()：
281472979692272
b 的形状：
[[0 1 2]
 [3 4 5]]
a 的形状：
[[0 1]
 [2 3]
 [4 5]]


In [25]:
b[0]=999
b,a

(array([[999, 999, 999],
        [  3,   4,   5]]),
 array([[999, 999],
        [999,   3],
        [  4,   5]]))