In [2]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [3]:
np.sin([20,30])

array([ 0.91294525, -0.98803162])

In [4]:
np.cos,np.tan,np.arcsin,np.arccos,np.arctan

(<ufunc 'cos'>,
 <ufunc 'tan'>,
 <ufunc 'arcsin'>,
 <ufunc 'arccos'>,
 <ufunc 'arctan'>)

In [5]:
np.around([1.8934343,9.324234324])

array([2., 9.])

In [6]:
np.around([1.8934343,9.324234324],3)

array([1.893, 9.324])

In [7]:
np.around([34341.8934343,234349.324234324],3)

array([ 34341.893, 234349.324])

In [8]:
np.around([34341.8934343,234349.324234324],-3)

array([ 34000., 234000.])

In [9]:
np.ceil,np.floor

(<ufunc 'ceil'>, <ufunc 'floor'>)

In [10]:
np.add,np.subtract,np.multiply,np.divide,np.divmod,np.mod,np.floor_divide,np.true_divide
np.mod  # 等价于
np.remainder

(<ufunc 'add'>,
 <ufunc 'subtract'>,
 <ufunc 'multiply'>,
 <ufunc 'divide'>,
 <ufunc 'divmod'>,
 <ufunc 'remainder'>,
 <ufunc 'floor_divide'>,
 <ufunc 'divide'>)

<ufunc 'remainder'>

<ufunc 'remainder'>

In [11]:
np.divide(9,4)
np.divmod(9,4)
np.true_divide(9,4)
np.floor_divide(9,4)

2.25

(2, 1)

2.25

2

In [12]:
a = np.random.randint(1,9,size=(3,5))
a

array([[6, 3, 5, 4, 4],
       [4, 7, 6, 1, 5],
       [8, 6, 7, 2, 7]])

In [13]:
np.reciprocal(a) # 整数数组的倒数默认元素类型还是整数

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [14]:
a = a.astype(np.float64)

In [15]:
np.reciprocal(a)
a

array([[0.16666667, 0.33333333, 0.2       , 0.25      , 0.25      ],
       [0.25      , 0.14285714, 0.16666667, 1.        , 0.2       ],
       [0.125     , 0.16666667, 0.14285714, 0.5       , 0.14285714]])

array([[6., 3., 5., 4., 4.],
       [4., 7., 6., 1., 5.],
       [8., 6., 7., 2., 7.]])