In [14]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [15]:
x = np.random.random(size=(4,5))
y = np.linspace(0,19,num=20).reshape(4,5)
x
y

array([[0.24024323, 0.34132515, 0.50050058, 0.79146315, 0.73414909],
       [0.99496251, 0.45196409, 0.25689666, 0.096035  , 0.07426025],
       [0.77290663, 0.81768643, 0.99684722, 0.37160459, 0.04310843],
       [0.85648707, 0.11904628, 0.10611208, 0.71501486, 0.68340595]])

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [17]:
np.save('out.npy',x)

In [18]:
np.load('out.npy')

array([[0.24024323, 0.34132515, 0.50050058, 0.79146315, 0.73414909],
       [0.99496251, 0.45196409, 0.25689666, 0.096035  , 0.07426025],
       [0.77290663, 0.81768643, 0.99684722, 0.37160459, 0.04310843],
       [0.85648707, 0.11904628, 0.10611208, 0.71501486, 0.68340595]])

In [5]:
type(_)

numpy.ndarray

In [19]:
np.savez('out2.npz',x,y)

In [7]:
np.load('out2.npz')

In [20]:
a2 = np.load('out2.npz')

In [21]:
a2['arr_0']  # 默认为arr_0,arr_1， 除非保存时指定关键字


array([[0.24024323, 0.34132515, 0.50050058, 0.79146315, 0.73414909],
       [0.99496251, 0.45196409, 0.25689666, 0.096035  , 0.07426025],
       [0.77290663, 0.81768643, 0.99684722, 0.37160459, 0.04310843],
       [0.85648707, 0.11904628, 0.10611208, 0.71501486, 0.68340595]])

In [22]:
np.savez('out3.npz',a=x,y=y)
a3 = np.load('out3.npz')

In [24]:
a3['a']

array([[0.24024323, 0.34132515, 0.50050058, 0.79146315, 0.73414909],
       [0.99496251, 0.45196409, 0.25689666, 0.096035  , 0.07426025],
       [0.77290663, 0.81768643, 0.99684722, 0.37160459, 0.04310843],
       [0.85648707, 0.11904628, 0.10611208, 0.71501486, 0.68340595]])

In [12]:
np.savetxt('arrtxt.txt',x,delimiter=':') # 默认为科学计数法
np.savetxt('arrtxtgz.gz',x) #支持直接读写压缩格式.gz
arr2 = np.loadtxt('arrtxt.txt',delimiter=':')
arr2

array([[0.60122879, 0.30774197, 0.60887845, 0.35814238, 0.91168724],
       [0.44746459, 0.08916946, 0.11618089, 0.31874207, 0.52482715],
       [0.95731889, 0.44171602, 0.05777017, 0.16709724, 0.24486649],
       [0.51064635, 0.69734866, 0.68033916, 0.18316742, 0.91457297]])