In [28]:
import numpy as np
from __future__ import unicode_literals
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [29]:
# np.matrix()
# np.mat()

In [30]:
ary = np.arange(1, 10).reshape(3,3)
m = np.matrix(ary, copy=True)  # default=True
ary 
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [31]:
m2 = np.mat(ary) # 数据共享的

In [32]:
m3 = np.mat('1 2 3; 4 5 6;7,8,9')
m3

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [33]:
np.asmatrix(ary) # 数据共享的

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

###矩阵的乘法

In [34]:
m3 * m3

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

### 逆矩阵
#### 若两个矩阵A、B满足：AB = BA = E （E为单位矩阵），则成为A、B为逆矩阵。

In [35]:
m3i * m3

matrix([[ -42,  -51,  -60],
        [ -78,  -96, -114],
        [-114, -141, -168]])

In [36]:
m4 = np.mat('3,8;2,-3')

In [37]:
m4.I

matrix([[ 0.12,  0.32],
        [ 0.08, -0.12]])

In [38]:
m4.I*m4

matrix([[ 1.00000000e+00, -5.55111512e-16],
        [ 0.00000000e+00,  1.00000000e+00]])

In [41]:
# ndarray提供了方法让多维数组替代矩阵的运算： 


a = np.array([
    [1, 2, 6],
    [3, 5, 7],
    [4, 8, 9]])
# 点乘法求ndarray的点乘结果，与矩阵的乘法运算结果相同
k = a.dot(a)
k2 = np.matrix(a) * np.matrix(a)
print(k, k2)
# linalg模块中的inv方法可以求取a的逆矩阵
l = np.linalg.inv(a)
print(l)

[[ 31  60  74]
 [ 46  87 116]
 [ 64 120 161]] [[ 31  60  74]
 [ 46  87 116]
 [ 64 120 161]]
[[-0.73333333  2.         -1.06666667]
 [ 0.06666667 -1.          0.73333333]
 [ 0.26666667  0.         -0.06666667]]


In [39]:
# np.linalg.solve() 解方程