In [1]:
import numpy as np

np.newaxis的功能:插入新维度

In [2]:
a=np.array([1,2,3,4,5])
print(a.shape)
print (a)


(5,)
[1 2 3 4 5]


In [3]:
a=np.array([1,2,3,4,5])
aa=a[:,np.newaxis]
print(aa.shape)
print (aa)


(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [4]:
a=np.array([1,2,3,4,5])
aa=a[np.newaxis,:]
print(aa.shape)
print (aa)


(1, 5)
[[1 2 3 4 5]]


对于[: , np.newaxis] 和 [np.newaxis，：]
是在np.newaxis这里增加1维

In [6]:
b = np.arange(10).reshape(2,-1)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
bb = b[:, np.newaxis]
bb

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [11]:
bb2 = b[:, np.newaxis,2]
bb2

array([[2],
       [7]])

In [12]:
bb3 = b[:,2]
bb3

array([2, 7])