In [9]:
from numpy.linalg import eig
import numpy as np
import datetime as dt
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

### 线性方程求解

In [7]:
def changeDate(dmy):
    dmy = str(dmy, encoding='utf-8')
    ti = dt.datetime.strptime(dmy, '%Y%m%d').date()
    t = ti.strftime('%Y-%m-%d')
    return t


stock = np.loadtxt('000607.csv', delimiter=',', usecols=(0, 2, 3, 4, 5),
                   skiprows=4000,
                   unpack=True,
                   max_rows=120,
                   dtype='M8[D],f8,f8,f8,f8', converters={0: changeDate})

dates, opening_prices, highest_prices, lowest_prices, closing_prices = stock

<pre>
ax + by + cz = d
bx + cy + dz = e
cx + dy + ez = f 

</pre>

$$
\left[ \begin{array}{cccc}
a & b & c \\
b & c & d \\
c & d & e \\
\end{array} 
\right ]
\times
\left[ \begin{array}{ccc}
w_0\\
w_1\\
w_2\\
\end{array} 
\right ]=
\left[ 
\begin{array}{ccc}
d\\
e\\
f\\
\end{array} 
\right ]
\\
\quad \quad  A \quad \quad \quad \quad \quad  x\quad \quad \quad \quad B  \quad
$$
x = np.linalg.lstsq(A,B)[0]

In [14]:
A = np.zeros((3, 3))
for j in range(3):
    A[j,] = closing_prices[j: j + 3]
B = closing_prices[3: 6]
A
B
x = np.linalg.lstsq(A,B, rcond=None)[0]
x

array([[3.99, 3.96, 3.56],
       [3.96, 3.56, 3.42],
       [3.56, 3.42, 3.38]])

array([3.42, 3.38, 3.38])

array([-0.00365905, -0.38874558,  1.39720003])

In [15]:
B.dot(x)

3.3960620902035212

In [16]:
true_value = closing_prices[6]
true_value

3.38

### 线性拟合

### 多项式拟合