归一化

In [7]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, scale, normalize
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [8]:
mms = MinMaxScaler(feature_range=(0, 1))
raw_samples = np.array([
    [17., 100., 4000],
    [20., 80., 5000],
    [23., 75., 5500]])

In [9]:
new_samples = mms.fit_transform(raw_samples)
new_samples

array([[0.        , 1.        , 0.        ],
       [0.5       , 0.2       , 0.66666667],
       [1.        , 0.        , 1.        ]])

In [10]:
mms.data_min_
mms.data_max_
mms.data_range_

array([  17.,   75., 4000.])

array([  23.,  100., 5500.])

array([   6.,   25., 1500.])

In [ ]:
mms.inverse_transform(_)

二值化

In [14]:
from sklearn.preprocessing import Binarizer

独热编码  onehot

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
import numpy as np
import sklearn.preprocessing as sp
raw_samples = np.array([
    [17., 100., 4000],
    [20., 80., 5000],
    [23., 75., 5500]])
# 创建独热编码器
ohe = sp.OneHotEncoder(sparse=False, dtype=int)
# 用独特编码器对原始样本矩阵做独热编码
ohe_dict = ohe.fit(raw_samples)
ohe_samples = ohe_dict.transform(raw_samples)

ohe_samples = ohe.fit_transform(raw_samples)
print(ohe_samples)

[[1 0 0 0 0 1 1 0 0]
 [0 1 0 0 1 0 0 1 0]
 [0 0 1 1 0 0 0 0 1]]


标签编码器  将字符串字段转变为数值

In [16]:
from sklearn.preprocessing import LabelEncoder
raw_samples = np.array([
    'audi', 'ford', 'audi', 'toyota',
    'ford', 'bmw', 'toyota', 'ford',
    'audi'])
print(raw_samples)
lbe = sp.LabelEncoder()
lbe_samples = lbe.fit_transform(raw_samples)
print(lbe_samples)
inv_samples = lbe.inverse_transform(lbe_samples)
print(inv_samples)

['audi' 'ford' 'audi' 'toyota' 'ford' 'bmw' 'toyota' 'ford' 'audi']
[0 2 0 3 2 1 3 2 0]
['audi' 'ford' 'audi' 'toyota' 'ford' 'bmw' 'toyota' 'ford' 'audi']


In [17]:
lbe.classes_

array(['audi', 'bmw', 'ford', 'toyota'], dtype='<U6')